version: 1
run:
  timeout: 10m

linters-settings:
  gocyclo:
    min-complexity: 15
  govet:
    enable:
      - shadow
  misspell:
    locale: US
  gosec:
    excludes:
      - G107
      - G204

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - goconst
    - gocyclo
    - gosec
    - dupl
    - nakedret
    - unconvert
    - unparam
    - whitespace

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: "cmd/"
      linters:
        - gochecknoglobals
    - text: "could not load export data"
      linters:
        - typecheck
    - text: "buildssa: failed to load package"
      linters:
        - typecheck
    - text: "modernc.org/sqlite"
      linters:
        - typecheck
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "should not use dot imports"
      linters:
        - revive
